# Generated by Django 4.1.5 on 2023-01-26 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliouser',
            old_name='user_mobile',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='portfoliouser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='portfoliouser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='portfoliouser',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='portfoliouser',
            name='user_password',
        ),
        migrations.AddField(
            model_name='portfoliouser',
            name='is_blogger',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfoliouser',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BlogUser',
        ),
    ]
