# Generated by Django 4.1.5 on 2023-01-26 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0004_portfoliouser_about_portfoliouser_heading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliouser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_portfolio', to=settings.AUTH_USER_MODEL),
        ),
    ]
