# Generated by Django 4.1.5 on 2023-01-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_userskill_rating_out_of_five_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskill',
            name='using_since',
            field=models.DateField(),
        ),
    ]
