# Generated by Django 4.1.5 on 2023-01-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_review_review_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client email',
                'verbose_name_plural': 'Client emails',
            },
        ),
    ]
