# Generated by Django 4.1.5 on 2023-01-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_clientlead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientlead',
            name='file_supporting_the_message',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/client_lead'),
        ),
    ]
