# Generated by Django 4.1.5 on 2023-01-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_alter_portfoliouser_profile_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientproject',
            name='project_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliouser',
            name='profile_short_description',
            field=models.TextField(),
        ),
    ]
