# Generated by Django 4.2 on 2023-04-13 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_alter_clientproject_tools_and_technologies_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userskill',
            old_name='using_since',
            new_name='last_used',
        ),
    ]
