name: Django CI/CD via AWS SSM

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Test and Deploy
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: portfolio_cum_blog.settings
      AWS_REGION: ${{ secrets.AWS_REGION }}
      INSTANCE_ID: ${{ secrets.EC2_INSTANCE_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run Pytest
        run: |
          source venv/bin/activate
          pytest

      - name: Deploy to EC2 via AWS SSM
        run: |
          aws ssm send-command \
            --region $AWS_REGION \
            --document-name "AWS-RunShellScript" \
            --comment "CI/CD Deploy Django App" \
            --targets "Key=instanceIds,Values=$INSTANCE_ID" \
            --timeout-seconds 300 \
            --parameters 'commands=[
              "cd /home/ubuntu/my_django_project/portfolio_cum_blog",
              "git pull origin main",
              "source ../env_app/bin/activate",
              "pip install -U pip",
              "pip install -r requirements.txt",
              "python manage.py migrate",
              "python manage.py collectstatic --noinput",
              "sudo systemctl restart gunicorn",
              "sudo systemctl reload nginx",
              "curl -fsS http://localhost || echo DEPLOYMENT WARNING: Health check failed"
            ]' \
            --output text
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
